build/cb_2017_us_county_20m.zip:
	mkdir -p $(dir $@)
	curl -o $@ http://www2.census.gov/geo/tiger/GENZ2017/shp/cb_2017_us_county_20m.zip
	unzip http://www2.census.gov/geo/tiger/GENZ2017/shp/cb_2017_us_county_20m.zip
